<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net6.0-windows</TargetFrameworks>
    <UseWpf>true</UseWpf>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>1.1.8</Version>
    <Title>WpfFlow</Title>
    <Authors>HuangMinQiang</Authors>
    <Company>HuangMinQiang</Company>
    <Description>WPF流程节点控件</Description>
    <Copyright>Copyright © 2026</Copyright>
    <PackageTags>Wpf Flow</PackageTags>
    <PackageReleaseNotes>流程节点连线支持曼哈顿路径和贝塞尔曲线路径</PackageReleaseNotes>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://gitee.com/huangminqiang/wpf-flow</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>Nuget_README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <Compile Remove="*.nupkg" />
    <Content Remove=".nupkg" />
    <None Remove=".nupkg" />

    <Compile Remove="icon.png" />
    <Content Remove="icon.png" />
    <None Remove="icon.png" />

    <Compile Remove="*.md" />
    <Content Remove="*.md" />
    <None Remove="*.md" />

    <Compile Remove="nuget_submit.txt" />
    <Content Remove="nuget_submit.txt" />
    <None Remove="nuget_submit.txt" />

    <Compile Remove="WpfFlow - 备份.csproj" />
    <Content Remove="WpfFlow - 备份.csproj" />
    <None Remove="WpfFlow - 备份.csproj" />

    <Compile Remove="WpfFlow.nuspec" />
    <Content Remove="WpfFlow.nuspec" />
    <None Remove="WpfFlow.nuspec" />

    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>

  <ItemGroup>
    <None Include="icon.png" Pack="true" PackagePath="icon.png" Visible="false" />
    <None Include="Nuget_README.md" Pack="true" PackagePath="Nuget_README.md" Visible="false" />
  </ItemGroup>

</Project>